#!/bin/bash

clear

#Installation of packages through the repositories
while read line
do
	sudo apt install --yes $line
done < /home/$USER/Documentos/pop-os-pos/list/repo

#Installation of flatpak packages
while read line
do
	flatpak install flathub -y $line
done < /home/$USER/Documentos/pop-os-pos/list/flat

#Actualization
sudo apt update && sudo apt upgrade

echo -e "\e[00;32mAll done\e[00m"
echo -e "\e[00;31mVerify if some error ocurred\e[00m"
read
